name: 'Upload Release Files'
description: 'Uploads all files matching glob pattern to a specified release'
author: robgonnella
inputs:
  github_token:
    description: 'The token to use to authenticate to the github api'
    required: true
  release_id:
    description: 'The release id to target'
    required: true
  file_pattern:
    description: 'The file glob pattern to use'
    required: true
runs:
  using: 'node12'
  main: 'gh_action_dist/index.js'
