ignore:
  - ".github/**/*"
  - "ardi/**/*"
  - "arguments/**/*"
  - "commands/**/*"
  - "**/docs/**/*"
  - "**/main.go"
  - "**/Makefile"
  - "**/*.md"
  - "v2/command/help.go"

coverage:
  range: "50...90"
