// Code generated by MockGen. DO NOT EDIT.
// Source: rpc.go

// Package mock_rpc is a generated GoMock package.
package mock_rpc

import (
	commands "github.com/arduino/arduino-cli/rpc/commands"
	gomock "github.com/golang/mock/gomock"
	rpc "github.com/robgonnella/ardi/v2/rpc"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// UpdateIndexFiles mocks base method
func (m *MockClient) UpdateIndexFiles() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIndexFiles")
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIndexFiles indicates an expected call of UpdateIndexFiles
func (mr *MockClientMockRecorder) UpdateIndexFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIndexFiles", reflect.TypeOf((*MockClient)(nil).UpdateIndexFiles))
}

// UpdateLibraryIndex mocks base method
func (m *MockClient) UpdateLibraryIndex() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLibraryIndex")
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLibraryIndex indicates an expected call of UpdateLibraryIndex
func (mr *MockClientMockRecorder) UpdateLibraryIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLibraryIndex", reflect.TypeOf((*MockClient)(nil).UpdateLibraryIndex))
}

// UpdatePlatformIndex mocks base method
func (m *MockClient) UpdatePlatformIndex() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlatformIndex")
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlatformIndex indicates an expected call of UpdatePlatformIndex
func (mr *MockClientMockRecorder) UpdatePlatformIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlatformIndex", reflect.TypeOf((*MockClient)(nil).UpdatePlatformIndex))
}

// UpgradePlatform mocks base method
func (m *MockClient) UpgradePlatform(platform string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradePlatform", platform)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpgradePlatform indicates an expected call of UpgradePlatform
func (mr *MockClientMockRecorder) UpgradePlatform(platform interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradePlatform", reflect.TypeOf((*MockClient)(nil).UpgradePlatform), platform)
}

// InstallPlatform mocks base method
func (m *MockClient) InstallPlatform(platform string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallPlatform", platform)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallPlatform indicates an expected call of InstallPlatform
func (mr *MockClientMockRecorder) InstallPlatform(platform interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallPlatform", reflect.TypeOf((*MockClient)(nil).InstallPlatform), platform)
}

// UninstallPlatform mocks base method
func (m *MockClient) UninstallPlatform(platform string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UninstallPlatform", platform)
	ret0, _ := ret[0].(error)
	return ret0
}

// UninstallPlatform indicates an expected call of UninstallPlatform
func (mr *MockClientMockRecorder) UninstallPlatform(platform interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UninstallPlatform", reflect.TypeOf((*MockClient)(nil).UninstallPlatform), platform)
}

// InstallAllPlatforms mocks base method
func (m *MockClient) InstallAllPlatforms() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallAllPlatforms")
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallAllPlatforms indicates an expected call of InstallAllPlatforms
func (mr *MockClientMockRecorder) InstallAllPlatforms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallAllPlatforms", reflect.TypeOf((*MockClient)(nil).InstallAllPlatforms))
}

// GetInstalledPlatforms mocks base method
func (m *MockClient) GetInstalledPlatforms() ([]*commands.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstalledPlatforms")
	ret0, _ := ret[0].([]*commands.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstalledPlatforms indicates an expected call of GetInstalledPlatforms
func (mr *MockClientMockRecorder) GetInstalledPlatforms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstalledPlatforms", reflect.TypeOf((*MockClient)(nil).GetInstalledPlatforms))
}

// GetPlatforms mocks base method
func (m *MockClient) GetPlatforms() ([]*commands.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatforms")
	ret0, _ := ret[0].([]*commands.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlatforms indicates an expected call of GetPlatforms
func (mr *MockClientMockRecorder) GetPlatforms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatforms", reflect.TypeOf((*MockClient)(nil).GetPlatforms))
}

// ConnectedBoards mocks base method
func (m *MockClient) ConnectedBoards() []*rpc.Board {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectedBoards")
	ret0, _ := ret[0].([]*rpc.Board)
	return ret0
}

// ConnectedBoards indicates an expected call of ConnectedBoards
func (mr *MockClientMockRecorder) ConnectedBoards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectedBoards", reflect.TypeOf((*MockClient)(nil).ConnectedBoards))
}

// AllBoards mocks base method
func (m *MockClient) AllBoards() []*rpc.Board {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllBoards")
	ret0, _ := ret[0].([]*rpc.Board)
	return ret0
}

// AllBoards indicates an expected call of AllBoards
func (mr *MockClientMockRecorder) AllBoards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllBoards", reflect.TypeOf((*MockClient)(nil).AllBoards))
}

// Upload mocks base method
func (m *MockClient) Upload(fqbn, sketchDir, device string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", fqbn, sketchDir, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload
func (mr *MockClientMockRecorder) Upload(fqbn, sketchDir, device interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockClient)(nil).Upload), fqbn, sketchDir, device)
}

// Compile mocks base method
func (m *MockClient) Compile(o rpc.CompileOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compile indicates an expected call of Compile
func (mr *MockClientMockRecorder) Compile(o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockClient)(nil).Compile), o)
}

// SearchLibraries mocks base method
func (m *MockClient) SearchLibraries(query string) ([]*commands.SearchedLibrary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchLibraries", query)
	ret0, _ := ret[0].([]*commands.SearchedLibrary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchLibraries indicates an expected call of SearchLibraries
func (mr *MockClientMockRecorder) SearchLibraries(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchLibraries", reflect.TypeOf((*MockClient)(nil).SearchLibraries), query)
}

// InstallLibrary mocks base method
func (m *MockClient) InstallLibrary(name, version string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallLibrary", name, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallLibrary indicates an expected call of InstallLibrary
func (mr *MockClientMockRecorder) InstallLibrary(name, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallLibrary", reflect.TypeOf((*MockClient)(nil).InstallLibrary), name, version)
}

// UninstallLibrary mocks base method
func (m *MockClient) UninstallLibrary(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UninstallLibrary", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UninstallLibrary indicates an expected call of UninstallLibrary
func (mr *MockClientMockRecorder) UninstallLibrary(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UninstallLibrary", reflect.TypeOf((*MockClient)(nil).UninstallLibrary), name)
}
