name: V1TEST

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - name: run ardi v1 tests
        run: |
          cd ~ && GO111MODULE=on go get github.com/robgonnella/ardi@latest
          ardi version
          ardi init -v
          ardi clean
