name: V2

on:
  push:
    tags:
      - 'v2.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: v2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - name: build
        run: 'make'
