name: V2TEST

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - name: test
        run: |
          cd v2 && make test-all
