name: V2

on:
  push:
    branches:
      - '*'
    paths:
      - 'v2/**'
    tags:
      - '!v*'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: v2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - name: install deps
        run: make deps
      - name: run ardi v2 tests
        run: make test-all
      - name: upload codecov report
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./scripts/upload-codecov.sh
