name: V2

on:
  push:
    branches:
      - '*'
    paths:
      - 'v2/**'
    tags:
      - '!v*'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: v2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - name: install golint
        run: go get -u golang.org/x/lint/golint
      - name: run ardi v2 tests
        run: 'make test-all'
      - name: coverage badge
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_SECRET }}
          gist_id: 4209bcb6a7198958ec0770b963684389
          gist_file_name: badge.json
          file_path: ./v2/badge.json
